title: Junya Yanagisawa (柳澤隼也)
logo: /assets/img/logo.png
description: <a href="index.html">[English]</a> <a href="index_jp.html">[日本語]</a><br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
